export { default as HomePage } from './Home';
export { default as FriendPage } from './Friend';
export { default as GroupPage } from './Group';
export { default as UserPage } from './User';
export { default as WatchPage } from './Watch';
export { default as LoginPage } from './Login';
export { default as MessengerPage } from './Messenger';
export { default as Page_Page } from './Page_';
export { default as NotificationsPage } from './Notifications';
